const sampleData = [
  {
    customer: "Rahul Sharma",
    city: "Mumbai",
    product: "Laptop",
    amount: 85000,
    status: "Completed",
  },
  {
    customer: "Priya Singh",
    city: "Delhi",
    product: "Mobile",
    amount: 42000,
    status: "Pending",
  },
  {
    customer: "Amit Patel",
    city: "Ahmedabad",
    product: "SSD",
    amount: 7200,
    status: "Completed",
  },
  {
    customer: "Sneha Verma",
    city: "Bengaluru",
    product: "Monitor",
    amount: 18500,
    status: "Processing",
  },
  {
    customer: "Arjun Nair",
    city: "Kochi",
    product: "Keyboard",
    amount: 3200,
    status: "Completed",
  },
  {
    customer: "Neha Kapoor",
    city: "Chennai",
    product: "Printer",
    amount: 12500,
    status: "Pending",
  },
  {
    customer: "Karan Mehta",
    city: "Pune",
    product: "Mouse",
    amount: 1800,
    status: "Completed",
  },
  {
    customer: "Vivek Rao",
    city: "Hyderabad",
    product: "Webcam",
    amount: 4800,
    status: "Processing",
  },
  {
    customer: "Pooja Shah",
    city: "Surat",
    product: "Tablet",
    amount: 32000,
    status: "Completed",
  },
  {
    customer: "Rohan Gupta",
    city: "Jaipur",
    product: "Headphones",
    amount: 6500,
    status: "Pending",
  },
  {
    customer: "Anjali Singh",
    city: "Bhopal",
    product: "Keyboard",
    amount: 1800,
    status: "Pending",
  },
  {
    customer: "Kunal Verma",
    city: "Noida",
    product: "Monitor",
    amount: 14500,
    status: "Completed",
  },
  {
    customer: "Rahul Nair",
    city: "Kochi",
    product: "External Hard Drive",
    amount: 6200,
    status: "Pending",
  },
  {
    customer: "Priya Sharma",
    city: "Jaipur",
    product: "Webcam",
    amount: 3500,
    status: "Completed",
  },
  {
    customer: "Rohan Mehta",
    city: "Chandigarh",
    product: "Laptop Bag",
    amount: 2200,
    status: "Completed",
  },
  {
    customer: "Meera Joshi",
    city: "Nagpur",
    product: "Mouse",
    amount: 1500,
    status: "Pending",
  },
  {
    customer: "Aditya Kumar",
    city: "Lucknow",
    product: "Tablet",
    amount: 28000,
    status: "Completed",
  },
  {
    customer: "Nisha Iyer",
    city: "Chennai",
    product: "Smart Watch",
    amount: 15500,
    status: "Completed",
  },
  {
    customer: "Sanjay Das",
    city: "Kolkata",
    product: "Router",
    amount: 2800,
    status: "Processing",
  },
  {
    customer: "Deepak Yadav",
    city: "Patna",
    product: "UPS",
    amount: 5600,
    status: "Completed",
  },
  {
    customer: "Aarti Mishra",
    city: "Varanasi",
    product: "Projector",
    amount: 38500,
    status: "Pending",
  },
  {
    customer: "Mohit Saini",
    city: "Gurugram",
    product: "Docking Station",
    amount: 9800,
    status: "Completed",
  },
  {
    customer: "Ishita Roy",
    city: "Kolkata",
    product: "Graphics Card",
    amount: 46500,
    status: "Completed",
  },
  {
    customer: "Harsh Jain",
    city: "Indore",
    product: "Office Chair",
    amount: 8900,
    status: "Processing",
  },
  {
    customer: "Divya Reddy",
    city: "Vijayawada",
    product: "Scanner",
    amount: 7400,
    status: "Completed",
  },
  {
    customer: "Nitin Kulkarni",
    city: "Nashik",
    product: "Printer Ink",
    amount: 2100,
    status: "Pending",
  },
  {
    customer: "Shreya Bose",
    city: "Bhubaneswar",
    product: "Microphone",
    amount: 5400,
    status: "Completed",
  },
  {
    customer: "Abhishek Tiwari",
    city: "Kanpur",
    product: "Power Bank",
    amount: 2600,
    status: "Completed",
  },
  {
    customer: "Manoj Pillai",
    city: "Thiruvananthapuram",
    product: "SSD",
    amount: 6800,
    status: "Completed",
  },
  {
    customer: "Kavya Menon",
    city: "Coimbatore",
    product: "Mechanical Keyboard",
    amount: 8900,
    status: "Processing",
  },
];

module.exports = sampleData;